### ISSUE TITLE
settings.cfg

### ISSUE THREAD

**Issue by Uborevich** [tarampampam/nod32-update-mirror#12]
Доброго времени суток.
Как настроить пути к директориям? 
Я начинающий в линуксе, и начал с того что поднял дома сервер ubuntu 14.04.1 с доступом из вне. Для демонстрации клиентам подготавливаемых им шаблонов (virtual host). Samba (доступ изнутри). utorrent server. Plex Mediaserver (домашняя развлекалка для жены). 
Вопрос встал о том что некоторые мои друзья "используют" меня для того чтоб я им обновлял базы нод. Все сводиться к поиску и введению валидного ключа из инета и обновлению баз. Т.к. недавно перенес инсульт, ходить по друзьям мне нелегко. вот собственно лирика.
Проза такова что пытаясь поставить на свой сервачек ваш скрипт не все понимаю.

Вроде скрипт производит работу но не вижу результатов. (файлов\архивов)
Вебморду тоже не удалось посмотреть.(скопировал все как вы описываете в ридми)

Я прошу помощи в установке и настройке Вашего скрипта. Дело в том что ннаверняка какието шаги Вы совершаете на автомате, или подразумеваете что их должны знать каждый. Я наверное из тех кто незнает/неумеет/недогадывается. 
Больше 20 лет с компьютером не расстаюсь, но всегда на винде был. Теперь ломаю привычный мир но новое пока дается нелегко и с усилием.

**Comment by Uborevich** [comment]
[image: Встроенное изображение 1]
Доброго времени суток. Вопрос собственно вот на картинке. последнее
обновление 25 марта. Индикатор в трее горит красным. Как проверить работу
скрипта на сервере? в чем может быть причина?

2014-11-18 15:33 GMT+06:00 kot <notifications@github.com>:

**Comment by tarampampam** [comment]
Я бы подсказал, если бы изображение, о котором идет речь - имело место быть :)

**Comment by Uborevich** [comment]
Вечер добрый. вот такие картинки - ничего не изменилось с тех пор.
Сорри что так много времени молчал - загремел в больницу.

2015-04-13 1:33 GMT+06:00 kot <notifications@github.com>:

**Comment by tarampampam** [comment]
Какие картинки? Открой нормально топик на гитхабе, не страдай почтовой херней

**Comment by Uborevich** [comment]
Сорри. Просто Вы сами мне на сервере устанавливали скрипт (я Вам давал рут)
и когда я Вам писал на гитхабе Вы просили в личку. Еще раз сорри.

17 апреля 2015 г., 22:52 пользователь kot <notifications@github.com>
написал:
