### ISSUE TITLE
Needs further improvements.

### ISSUE THREAD

**Issue by remlei** [tarampampam/nod32-update-mirror#14]
There's no issue on the script and it works but it downloads a lot of junk in process and it waste CPU cycle at start parsing the update.ver (taking it a while to process the update to download) this also it needs to improve the following:

- able to select what type of product to cache the updates (eg, Antivirus or Smart Security)
- able to bypass other language packs (we are downloading about 1gigs of junk versus a 120mb of important files)
- learn to use sed to parse and check the if the file currently downloaded is updated or not. Instead of parsing the update.ver before downloads. It can check the version on the fly by checking the "versionid=" on the nup files and one from update.ver; if didnt match then it downloads.

All of those issues are not present using this script from a russian forum: http://wl500g.info/showthread.php?7877-NOD32-update-server . It runs in every linux flavor as long as you had the depencies installed (sed, unrar, touch-coreutils)

It does do the job and with minor editing on the main script file to accept downloads on v6,v7 and v8 eset products.

**Comment by tarampampam** [comment]
Check now, please: https://github.com/tarampampam/nod32-update-mirror/commit/ed1671c06ee39dfcc649c3648a24c4da4ead5daa, **[download last version](https://github.com/tarampampam/nod32-update-mirror/archive/master.zip)**

**Comment by remlei** [comment]
nice improvement so far, still need some adjustments here and there

- can you test it under archlinux platform? it throws me an error like this
[07:18:20] Getting valid key from '/home/nod32upd/getkey.sh'.. /home/nod32upd/getkey.sh: line 1: #!/bin/bash: No such file or directory
/home/nod32upd/settings.cfg: line 1: #!/bin/bash: No such file or directory
Ok (xxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxx)

Nevertheless the entire script is still working despite of that error.
I got all package required like wget, curl and unrar. Bash is installed by default on archlinux, reinstalled it just to be sure and still the error is there. Or maybe im missing something here...

- able to bypass /v3-rel-sta/ directory and just download the files directly according what you set on checkSubdirsList= on setting.cfg... im still wasting about 120megs of old update files here that was last updated since 2004. So in my case, I want to cache updates on v8 directory, so the script should be only downloading those v8 files.

- parsing update.ver is still there, before it replaces the old update.ver, it should check if the current update.ver is updated or not, So even if I set it to run every 30mins, if the files are up to date, it should just throw me a message that my cached updates are up-to-date, instead of recheking all the files again if it was updated or not.

**Comment by tarampampam** [comment]
То ли ты активно юзаешь google.translate, то ли ещё какое дерьмо.. Ридми - на русском, все тикеты обсуждаются - на русском, давай не будем выделываться?

**Comment by remlei** [comment]
already downloaded the latest version as I posted my findings above. At least that's what you telling me on a translated text (so dont blame me if I dont get what you exactly saying right now).

Although I did edit the code and delete some of portions (or quoted) of the code to make it do what I want to, which skip the v3/v4 updates. and download the specific v5-v8 files. Which I guess you can do that also, commenting out a code is quite easy.
