### ISSUE TITLE
Изменения в базах NOD и переставший работать get-nod32-key.sh

### ISSUE THREAD

**Issue by EvilBox** [tarampampam/nod32-update-mirror#15]
Приветствую,
Не знаю туда ли я пишу, хочу донести до вас что в скрипте get-nod32-key.sh имеются неточности из-за изменений в базах нода.

А именно 73 строка: local TestPath='/v3-rel-sta/mod_000_loader_1080/em000_32_l0.nup';
Ее лучше заменить на: local TestPath='/v3-rel-sta/mod_000_loader_1082/em000_32_l0.nup';
Т.к файла по старому пути на серверах eset больше нет

Так же, 
Строка 110: keysList+=$(curl -s http://www.nod327.net/ |\
К сожалению сайт http://www.nod327.net умер, может его стоит сменить на http://tnoduse2.blogspot.ru который использует tnod? К сожалению я не знаю как изменить парсер, с этим блогом скрипт не правильно его обрабатывает, с мусором и без паролей, хотя curl пароли успешно получает, т/е на сайте нет скриптов скрывающих их.

Спасибо!

**Comment by cryol** [comment]
curl -s http://tnoduse2.blogspot.ru |    sed -e 's/<[^>]*>//g' |    awk -F: '/((TRIAL|EAV)-[0-9]+)|(Password: [a-z0-9]+)/ {print $2}' | sed -e 's/ //g' |    tr -d "\r" | awk '{getline b;printf("%s:%s\n",$0,b)}'

**Comment by cryol** [comment]
curl -s http://tnoduse2.blogspot.ru |    sed -e 's/<[^>]*>//g' |    awk -F: '/((TRIAL|EAV)-[0-9]+)|(Password: [a-z0-9]+)/ {print $2}' | sed -e 's/ //g' |    tr -d "\r" | awk '{getline b;printf("%s:%s\n",$0,b)}'

**Comment by tarampampam** [comment]
Спасибо ребят за отклик, изменения внес, проверяйте.

[changed TestPath](https://github.com/tarampampam/nod32-update-mirror/blob/master/nod32upd/get-nod32-key.sh#L73), [curl tnoduse2.blogspot.ru](https://github.com/tarampampam/nod32-update-mirror/blob/master/nod32upd/get-nod32-key.sh#L105)
