### ISSUE TITLE
Нужна помощь

### ISSUE THREAD

**Issue by viris42** [tarampampam/nod32-update-mirror#19]
То ли я тупой толи сани не едут. Подскажите пожалуйста как прикрутит web морду к Apache 2.x. Где сам index.html ? Все заведено на виртуалку http://xxxxxxx.xxxx.xxx:8084

**Comment by tarampampam** [comment]
Начнем издалека - для чего нужны файлы `.htaccess`?

**Comment by viris42** [comment]
Re: [nod32-update-mirror] Нужна помощь (#19)



Здравствуйте, kot.

Вы писали 27 февраля 2015 г., 6:20:42:





Начнем издалека - для чего нужны файлы .htaccess?
—
Reply to this email directly or view it on GitHub.



Я понимаю, что в .htaccess делается переназначение. Но там то указан index.html
Вот то, что указано 
<IfModule mod_dir.c>
 DirectoryIndex index.html
</IfModule>



-- 
С уважением,
 Роман                          mailto:admin@viris42.zyns.com

**Comment by tarampampam** [comment]
1. Всё должно заработать ничего не меняя в большинстве случаев
2. Обязательно прочитать про дерективы апача, т.к. вы пытаетесь именно ими манипулировать, но складывается мнение, что вы не совсем понимаете их предназначения
3. Очень желательно посмотреть в сторону этих строк, т.к. именно они должны подтолкнуть к пониманию как она работает:
```apache
  ##### Path to webface files ####
  HeaderName /.webface/header.html
  ReadmeName /.webface/footer.html
```

**Comment by viris42** [comment]
Re: [nod32-update-mirror] Нужна помощь (#19)



Здравствуйте, kot.

Вы писали 27 февраля 2015 г., 22:12:33:






Всё должно заработать ничего не меняя в большинстве случаев
Обязательно прочитать про дерективы апача, т.к. вы пытаетесь именно ими манипулировать, но складывается мнение, что вы не совсем понимаете их предназначения
Очень желательно посмотреть в сторону этих строк, т.к. именно они должны подтолкнуть к пониманию как она работает:

  ##### Path to webface files ####
  HeaderName /.webface/header.html
  ReadmeName /.webface/footer.html
—
Reply to this email directly or view it on GitHub.



Вот эти строки мне и не понятны. Я не спец в этом деле. Делаю все по примерам из инета.


-- 
С уважением,
 Роман                          mailto:admin@viris42.zyns.com

**Comment by tarampampam** [comment]
Значит не нужно стесняться, [давайте вместе поищем](http://lmgtfy.com/?q=apache+HeaderName&l=1) и почитаем, что же за магию делают эти строки.

Когда придет понимание тем действиям, которые воспроизводятся, и сформируются предметные вопросы (не _"а что это делает?"_ и _"я делаю так-то и так-то, ожидаю вот такой результат, а вместо него получаю вот такой?"_) - я с удовольствием вас проконсультирую.

**Comment by viris42** [comment]
Re: [nod32-update-mirror] Нужна помощь (#19)



Здравствуйте, kot.

Вы писали 27 февраля 2015 г., 22:52:04:





Значит не нужно стесняться, давайте вместе поищем и почитаем, что же за магию делают эти строки.
Когда придет понимание тем действиям, которые воспроизводятся, и сформируются предметные вопросы (не "а что это делает?" и "я делаю так-то и так-то, ожидаю вот такой результат, а вместо него получаю вот такой?") - я с удовольствием вас проконсультирую.
—
Reply to this email directly or view it on GitHub.



Все заработало.
А вот в логе появляется при обновлении
Вывод команды /media/hdd/var/nod32upd/update.sh > /dev/null ..
/media/hdd/var/nod32upd/settings.cfg: line 1: ﻿#!/bin/bash: No such file or directory
/media/hdd/var/nod32upd/getkey.sh: line 1: ﻿#!/bin/bash: No such file or directory
/media/hdd/var/nod32upd/settings.cfg: line 1: ﻿#!/bin/bash: No such file or directory

-- 
С уважением,
 Роман                          mailto:admin@viris42.zyns.com

**Comment by tarampampam** [comment]
1. Зачем вывод отправлять в /dev/null, если он вам нужен?
2. [Давайте будем учиться самостоятельно искать ответы на простые и очевидные вопросы](http://lmgtfy.com/?q=line+1%3A+%EF%BB%BF%23!%2Fbin%2Fbash%3A+No+such+file+or+directory)
