### ISSUE TITLE
How to add version number on webface ?

### ISSUE THREAD

**Issue by mumet** [tarampampam/nod32-update-mirror#22]
How to add version number on webface ?

Example:
Last Update: 21-04-2015
Virus signature database Version: 11508
Link Demo: http://goo.gl/WaZF7i

Please help me.

Thanks

**Comment by tarampampam** [comment]
Hand parse update.ver file. This script cant do it now.

**Comment by to03** [comment]
This parse 
$grab=@file_get_contents("update.ver");
$grab = ereg_replace('(.*)ENGINE2]','', $grab); 
if ($grab!="") {
  eregi("versionid=([0-9\.]+)",$grab,$pocket);
  //eregi("\(([0-9]{4})([0-9]{2})([0-9]{2})\)",$grab,$pocket2);
  eregi("date=([0-9\.]+)",$grab,$pocket2);
//  $txt=$pocket[1]." OT (".$pocket2[3].".".$pocket2[2].".".$pocket2[1].")";
  $txt=" {$pocket[1]} ({$pocket2[1]})";
//  echo $txt;
}
else {
  $txt=" No connection :(";
}

только с bash не дружу. Это на php
