### ISSUE TITLE
Проблема с запуском на Freebsd 9.3

### ISSUE THREAD

**Issue by dsd10** [tarampampam/nod32-update-mirror#23]
Здравствуйте.
Устанавливал ваш скрипт прошлой версии на linux ubuntu - там он работал. Хотел попробовать установить новую версию на freebsd 9.3.
При запуске getkey либо update выдает такие строки если вначале файла стоит /bin/bash: 
./update.sh: Command not found.

Если поставить /bin/sh то выдает такое:
[root@dc /home/nod32upd]# ./update.sh
./update.sh: source: not found
./update.sh: 153: Syntax error: "(" unexpected

update внутри изменил только путь, более ничего не трогал, если не считать самую первую строку  bash и sh
------------------------
[root@dc /home/nod32upd]# bash --version
GNU bash, version 4.3.33(0)-release (i386-portbld-freebsd9.3)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
------------------------
[root@dc /home/nod32upd]# wget -V
GNU Wget 1.16.2 built on freebsd9.3.

+digest +https -ipv6 +iri +large-file +nls +ntlm +opie -psl +ssl/openssl

Wgetrc:
    /usr/local/etc/wgetrc (system)
Locale:
    /usr/local/share/locale
Compile:
    cc -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/usr/local/etc/wgetrc"
    -DLOCALEDIR="/usr/local/share/locale" -I. -I../lib -I../lib
    -I/usr/local/include -I/usr/include -D_THREAD_SAFE
    -I/usr/local/include -I/usr/local/include -DNDEBUG -O2 -pipe
    -fno-strict-aliasing
Link:
    cc -I/usr/local/include -DNDEBUG -O2 -pipe -fno-strict-aliasing
    -L/usr/local/lib -L/usr/lib -Wl,-rpath,/usr/lib:/usr/local/lib
    -L/usr/local/lib /usr/local/lib/libiconv.so -Wl,-rpath
    -Wl,/usr/local/lib /usr/local/lib/libintl.so
    /usr/local/lib/libiconv.so -Wl,-rpath -Wl,/usr/local/lib
    /usr/lib/libssl.so /usr/lib/libcrypto.so -lz -lidn ftp-opie.o
    openssl.o http-ntlm.o ../lib/libgnu.a

Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Originally written by Hrvoje Niksic <hniksic@xemacs.org>.
Please send bug reports and questions to <bug-wget@gnu.org>.
------------------------------

Может надо установить какие то пакеты совместимости?
UPDATE:
Установил linux_base-f10, заработало... Простите за беспокойство. :)

**Comment by tarampampam** [comment]
Ничего страшного, спасибо за решение :+1:
