### ISSUE TITLE
Wget и нули внутри скачаного файла

### ISSUE THREAD

**Issue by ghostku** [tarampampam/nod32-update-mirror#24]
Столкнулся с такой проблемой: Нод перестал обновлятся, ругался на ошибку при скачивании файлов. У меня Ваш скрипт работает на нескольких компьютерах и я сравнил файлы обновления, обнаружил разбежность. Один из файлов (https://mega.nz/#!IIBjCIgY!v0fTEd8txWZD_ineicqu9_BdOfeWThMGn183JyCRWzc) имел такой же размер как и правильный файл но по содержимому и по дате  создания отличался от него. Внутри вместо части данных были просто нули. Более того, так как поврежденный файл получил дату создания "сегодняшним" числом а правильная дата в оригинальном файле старше, то по логике wgeta поврежденный файл не будет  перезаписан во время следующего обновления пока не выйдет его новая версия.
Хотелось бы чтобы скрипт хотя умел сам исправлять подобные ситуации.
- В идеале научится бы проверять файлы обновления так как их проверяет сам Антивирус, ведь внутри каждого файла указан размер и CRC, правда, насколько я понимаю алгоритм вычисления неясен.
- Также было бы достаточно если бы wget умел перекачивать файлы не только когда они более новые чем файлы на локальном компе, но и когда их дата создания просто отличается.
- В качестве костыля можно предложить вариант перед обновлением искать sed`ом и удалять все файлы в которых встречается к примеру 0x000000 так как реальных файлах та последовательность не встречается.

Интерессно было бы понять почему wget умудрился так скачать файл, но это было пару дней назад и логов у меня не осталось

**Comment by tarampampam** [comment]
Категорически приветствую!

Приложенный тобой файл действительно имеет нарушенную структуру. Но нарушенную в самом теле, а не целиком. Причина может быть различная - от неполадки сетевого соединения, до ошибки во время записи файла, или же "глюк" самого `wget`.
* Считать CRC можно, но не сверить с удаленным файлом (*на источнике*) пока его не скачаешь - смысл контрольных сумм теряется.
* `wget` и так запускается с флагом `--timestamping`.
* Костыль считаю что смысла не имеет, так как это проблема не на стороне скрипта. Лечить язву путем прикладывания подорожника - не лучшая идея.

Как альтернативное решение - запускать `update.sh --flush` время от времени.

**Comment by ghostku** [comment]
По поводу причины:
Я тут вспомнил что бывали моменты когда wget оччень долго качал файл (около часа файл весом в пару мегабайт) в итоге все докачивал и ишел далее, может именно в таких случаях он не может получить файл с сервера и забивает его нулями? Можно ли заставить wget писать подробный лог чтобы потом его проанализировать?

- Про CRC я имел ввиду что внутри nup файла есть поля size - который меньше реального размера файла и CRC Наверняка эта контрольная сума считается от какой-то части файла самим антивирусом при проверке целосности обновления, но алгоритм нам неизвестен.
- timestamping перекачает файл только если дата на сервере будет новее чем на клиенте, а нам неплохо было бы если бы файл перекачивался в любом случае когда дата на сервере не равна дате на клиенте. Мне кажется это как раз то место куда можно воткнуть костыль.

**Comment by tarampampam** [comment]
> Можно ли заставить wget писать подробный лог чтобы потом его проанализировать?

Можно. Попробуй скачать "проблемные" файлы самостоятельно с флагом дебага:

```help
-d --debug
Turn on debug output, meaning various information important to the developers of Wget if it does
not work properly. Your system administrator may have chosen to compile Wget without debug
support, in which case -d will not work. Please note that compiling with debug support is always
safe---Wget compiled with the debug support will not print any debug info unless requested with -d.
```

Например: 
```bash
$ wget --debug http://update.eset.com/v3-rel-sta/mod_002_engine_24849/em002_32_l0.nup
```

При наличии более подробной информации о "проблемном" поведении можно о чем то думать. Пока что воспроизвести описанное тобой выше поведение - не удается, а как следствие -  предпринимать какие-либо действия решению.

> но алгоритм нам неизвестен

Очень точное замечание :)

> неплохо было бы если бы файл перекачивался в любом случае когда дата на сервере не равна дате на клиенте. Мне кажется это как раз то место куда можно воткнуть костыль.

Хотите "перекачивать" все файлы в любом случае? Делайте `update.sh --flush` перед запуском обновления. В любом другом случае (*если предварительно файл скачивать*) - теряется смысл слова "обновление" (обновление = скачивание только тех файлов, которые *обновлены*). Если есть желание попытаться "воткнуть костыль" в момент проверки даты самим `wget` - поделитесь, пожалуйста результатами отладки или переписывания исходников `wget` (`GNU`) - довольно интересно что получится в итоге.

Пожалуйста, предоставь более подробную информацию о том, как именно воспроизводится проблема. А именно:
```bash
$ cat /proc/version
$ bash --version
$ wget -V
```
И собственно сам подробный лог возникновения ошибки. В противном случае ничем помочь - не смогу.

**Comment by ghostku** [comment]
На данный момент  решил раз в сутки запускать `update.sh --flush` но подумаю как бы прикрутить проверку даты, возможно `curl`
