### ISSUE TITLE
Пара вопросов непосредственно про обновления

### ISSUE THREAD

**Issue by ghostku** [tarampampam/nod32-update-mirror#25]
Я никогда раньше особо не вникал в принцип обновления НОДа поэтому вопросы могут показатся глупыми но всё же:
1 Некоторые файлы в подпапках v5, v6, v7 вроде как одинаковы почему так? Скрипт создает симлинки или качает каждый файл заново?
2 Обязательно ли указывать в качестве сервера обновления в самом НОДе путь с подпапками (например http://server.com:80/v5/ для пятой версии) или можно всех обновлять с корня? Какие подводные камни? Как я понимаю если не указать подпапку то обновления компонентов к примеру не произойдет, ведь компоненты лежат каждый в своей подпапке
3 Кстати о компонентах: у меня было запущено два сервера с Вашим скриптом и одинаковыми настройками на них После пары дней работы на одном из серверов в подпапке /v5/ лежали файлы eav**be**\*.nup и ess**be***.nup а на другом их не было. Я так предполагаю это мне както случайно повезло с ключем но точно не уверен.

**Comment by tarampampam** [comment]
1. Да, они одинаковые, @tyllo [даже написал решение](https://github.com/tarampampam/nod32-update-mirror/pull/18), но я пока его не внедрил. Возможно, в скором времени этим займусь. Скипт качает их заново
2. Нет, пути к подпапкам указывать не обязательно. Клиент сам с этим разбирается, можно обновлять всех с корня
3. Врятли дело в ключе, если узнаете почему - буду признателен этой информации

**Comment by hempalex** [comment]
C компонентами все дело в том что в подпапках vX разные update.ver
Но компоненты там старые, самые первые версии.

Официальный ответ от поддержки на предмет как обновлять Business Edition http://support.eset.com/kb3308/

Я просто вытащил скриптом адреса нужных мне nup и txt (только enu и rus), и затем просто сделал cat *_update.ver.txt >> update.ver, но скрипт увы на php - я так виртуозно shell-ом не владею :-)
И после обновления NOD предложил обновиться, но работает только для 5-ой версии.
В принципе было бы здорово иметь поддержку интеграции апдейтом в этой kb (статья видимо обновляется регулярно).
