### ISSUE TITLE
getkeys опять перестал работать

### ISSUE THREAD

**Issue by Hark0nnen** [tarampampam/nod32-update-mirror#26]
local TestPath='/v3-rel-sta/mod_000_loader_1082/em000_32_l0.nup';
файл не сушествует, вместо него '/v3-rel-sta/mod_000_loader_1092/em000_32_l0.nup'

**Comment by tarampampam** [comment]
Да, действительно, спасибо за оперативный отклик! [Апдейт](https://github.com/tarampampam/nod32-update-mirror/commit/34390a3a6f4ff66a7051216b3a098d8993c3494a) был выпущен
