### ISSUE TITLE
Извените! Может пишу не сюда!

### ISSUE THREAD

**Issue by sweettoxic** [tarampampam/nod32-update-mirror#28]
У меня ниская скорость! иногда все зависает! хотел уточнито по поводу пораметра "updTypes" Если у меня продукты только ess, eav, bess, можно оставить только их? Чтобы не качать обновления для других продуктов. Правильно ли я понимаю? Заранее спасибо!

**Comment by tarampampam** [comment]
1. Для скачивания файлов обновлений используется wget - проверьте стабильность и скорость его работы на любых других более-и-менее тяжелый файлах;
2. Экспериментируйте :) Откройте оригинальный файл `update.ver` и поищите ответ в его содержимом

**Comment by DRON4eg** [comment]
Решил не делать новый тиккет.
у меня такая же проблема со скоростью на Debian 8, и иногда загрузка вообще зависает не могу понять в чём дело. Большие файлы грузит на ура, скорость нормальная, закачка не обрывается, пробовал отсюда качать http://speedcheck.gldn.net/ 1000МБ
на CentOS 6.7 скорость более минее приемлемая и закачка не обрывается
почему на дебиане такая проблема не понятно, прошу посильной помощи :)

**Comment by tarampampam** [comment]
Можно одним словом? Хуйзнает. Вот честно.

**Comment by DRON4eg** [comment]
ГЫ) можно конечно)) я в принципе ожидал такого ответа))) но думал, может хоть пнёте в нужную сторону в решении проблемы))

**Comment by maximsource** [comment]
решил не создавать новую тему

последнее время что-то случилось с проверкой ключей
подсовываю в файл точно рабочие триальные ключи EAV (проверял вручную),, а скрипт их откидывает как нерабочие
