### ISSUE TITLE
Error 0x1106 on ESET higher than version 4

### ISSUE THREAD

**Issue by remlei** [tarampampam/nod32-update-mirror#29]
As title says, updates fine on version 4 but not on v5 and higher. It throws error 0x1106

- my suspect is due to missing cached update files, not sure what exactly files are that or somethings wrong with the update.ver (not sure)

- using the old-style script for caching ESET updates works just fine (since it cache all the updates minues the language updates and version upgrade nups. 

http://wl500g.info/showthread.php?7877-NOD32-update-server 

which is I actually modified a little to cache updates from v7 and above (including v9).

- updating using v9 is certainly not working at all, it checks for updates but not updating at all (no errors), using my old-style script did work though.

All of this was done via iptables interception and lighttpd with alias.url module so I can redirect the files that actually works like official update server, without any kind of registry hacks to set update servers manually. I do this because we had like 8 computers using a ESET products that is actually nice to have the ESET Cache update running on my NAS box (nas4free).

**Comment by Hark0nnen** [comment]
Noticed this too. Its broke about 3 weeks ago i think. Curiously update on v5+ works once after installation, but subsequent updates fail with 0x1106.

**Comment by m-kozlowski** [comment]
There are two problems with running mirror for multiple versions:
1: HOSTS section in resulting update.ver is hardcoded to use /v7/ urls.
    This forces **any version of client** to get subsequent updates from /eset_upd/v7/update.ver
2: nod version 9 introduces 64bit variants of modules that are not included in default settings.cfg.
    in particular: advheur64, archives64, cleaner64, db64, engine64, horus64, iris64, opp64, parental64, pegasus64, perseus64, protoscan64,smon64, speclean64
    Not sure if all of those are essential, but with those included my mirror works fine.
