### ISSUE TITLE
Ошибка в update.sh?

### ISSUE THREAD

**Issue by Kontus** [tarampampam/nod32-update-mirror#31]
Я не специалист в **Bash**, но, насколько я понимаю, здесь что-то не так:
```bash
if [ -n "$wgetDelay" ] || [ -z "$wgetDelay" ]; then
  wgetDelay='0';
fi;

if [ -n "$wgetLimitSpeed" ] || [ -z "$wgetLimitSpeed" ]; then
  wgetLimitSpeed='102400k';
fi;
```
Переменные **wgetDelay** и **wgetLimitSpeed** у меня, вне зависимости от того, определены они или нет в _**settings.cfg**_, принимают значения **0** и **102400k** соответственно.

_Debian 8.2, Bash 4.3.30_

**Comment by tarampampam** [comment]
Да, спасибо за замечание, моя не внимательность :) Уже всё поправил
