### ISSUE TITLE
Маленький fix для nod32-mirror

### ISSUE THREAD

**Issue by karavan750** [tarampampam/nod32-update-mirror#32]
В конфиге переменной BASEPATH лучше умолчательным значением присвоить
$(dirname $(readlink -e $0))

**Comment by tarampampam** [comment]
Эм.. А почему именно так, а не так как сейчас?
```bash
BASEPATH=$(dirname $0);
```

**Comment by karavan750** [comment]
Николай, $(dirname $0) возвращает относительный путь запуска скрипта,
а $(dirname
$(readlink -e $0)) вернет абсолютный.
В случае, когда мы не знаем откуда запускается скрипт, то лучше искать
абсолютный путь.

2015-11-24 12:38 GMT+03:00 kot <notifications@github.com>:

> Эм.. А почему именно так, а не так как сейчас?
>
> BASEPATH=$(dirname $0);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tarampampam/nod32-update-mirror/issues/32#issuecomment-159208551>
> .
>



-- 
С уважением,
Деревянко Сергей

+7(967)073-24-21
mailto: karavan750@gmail.com

**Comment by tarampampam** [comment]
Да, резонно. Поправку внес. Спасибо!
