### ISSUE TITLE
Can you add a variable to identify a version of the virus database

### ISSUE THREAD

**Issue by laoqiuqiu** [tarampampam/nod32-update-mirror#34]
Can you add a variable to identify a version of the virus database.

I did it. Insert into 380 rows:
```bash
if [ "$SectionName" == 'ENGINE2' ]; then
  local Version=$(getValueFromINI "$sectionContent" "version");
  echo "$Version" > $saveToPath'LastVersion.txt';
fi;
```

**Comment by tarampampam** [comment]
This is not correct way. We have a lot of sections in file `update.ver`, and each of it have version of different "products". For example - why we must take value from `ENGINE2` and not from `ENGINE1` or `ENGINE0`?

**Comment by laoqiuqiu** [comment]
Is that a list that should be set up to store the corresponding version number, and then take the maximum?

**Comment by laoqiuqiu** [comment]
Recent EES version of the V5 update prompted me to the end of the accident.

I changed the 348 line. Will not have the impact?
  echo -e "[HOSTS]\nOther=100@http://um01.eset.com/eset_upd/$version, \
100@http://91.228.166.14/eset_upd/$version, 100@http://um03.eset.com/eset_upd/$version, \
100@http://91.228.166.16/eset_upd/$version, 100@http://um05.eset.com/eset_upd/$version, \
100@http://91.228.167.133/eset_upd/$version, 100@http://um07.eset.com/eset_upd/$version, \
100@http://38.90.226.37/eset_upd/$version, 100@http://um09.eset.com/eset_upd/$version, \
100@http://38.90.226.39/eset_upd/$version, 100@http://um11.eset.com/eset_upd/$version, \
100@http://38.90.226.40/eset_upd/$version, 100@http://um21.eset.com/eset_upd/$version, \
100@http://91.228.167.21/eset_upd/$version\n" > $newVerFile;

**Comment by tarampampam** [comment]
No, as I think `[HOSTS]` section is not important for us because in any case case nod32 will ignore it.

**Comment by tarampampam** [comment]
About version of the virus database - this feature was added. Test it now, please.

5978e857ac88c54278144906ec22477e8ce735f6
