### ISSUE TITLE
v3 update issue

### ISSUE THREAD

**Issue by CNMan** [tarampampam/nod32-update-mirror#36]
I add 'v3' to https://github.com/tarampampam/nod32-update-mirror/blob/master/nod32upd/settings.cfg#L68 , but it don't mkdir v3, just download all file to pathToSaveBase.

**Comment by Hark0nnen** [comment]
Thats exactly how it should be. v3 didnt look for any subfolders. 
P.S. Are v3 updates ever working? I vaguely remember it stopped updating correctly few years ago...

**Comment by CNMan** [comment]
![2016-02-05_020937](https://cloud.githubusercontent.com/assets/8692234/12824756/bf02df4e-cbad-11e5-9686-85eb02b7dcfe.png)
files download from http://update.eset.com/v3-rel-sta/
