### ISSUE TITLE
Проблема с проверкой ключей

### ISSUE THREAD

**Issue by DimonUA** [tarampampam/nod32-update-mirror#38]
НОД походу поменял структуру сервера.

В файле getkey.sh в 67-й строке поменяйте
`local TestPath='/v3-rel-sta/mod_000_loader_1092/em000_32_l0.nup';`
на
`local TestPath='/v3-rel-sta/mod_000_loader_1098/em000_32_l0.nup';`
Кстати, не лучше будет использовать 
`local TestPath='/eset_upd/update.ver';`?

**Comment by cra3y** [comment]
Я решил данную проблему добавлением кода 404(not found) в список успешных
`if [ "$code" == "200" ] || [ "$code" == "304" ] || [ "$code" == "404" ]; then`
То есть, если нам говорят, что файла нет, то мы успешно залогинились.

**Comment by maximsource** [comment]
насчет
local TestPath='/eset_upd/update.ver';
не лучше
http://update.eset.com/eset_upd/update.ver доступен без авторизации

**Comment by soyokaze** [comment]
Пара вещей, которые я обнаружил, исправляя эту проблему у себя:
1. Судя по всему, обновления некоторых модулей недоступны при использовании триальных ключей (например, `/v8-rel-sta/mod_010_smon_1036/em010_32_l0.nup`).
2. В getkey.sh, в строке 99 такой вызов curl будет работать только с IP, находящихся в РФ. Для всех остальных blogspot вернет не страницу, а перенаправление на другой домен. Так что надо заменить `curl -s` на `curl -sL`.

**Comment by kostya740** [comment]
По советам выше сделал следующее и теперь скрипт работает.
1. добавил в фаил фф обработку 404 ошибки
`if [ "$code" == "200" ] || [ "$code" == "304" ] || [ "$code" == "404" ];`
2. В getkey.sh, в строке 99 заменить curl -s на curl -sL.

**Comment by tarampampam** [comment]
Очень извиняюсь за задержку в исправлениях. @soyokaze - спасибо за патч и экономию моего времени, изменения внес

https://github.com/tarampampam/nod32-update-mirror/commit/526f27eeed5813ca17bfa1252901865ebd68c774
