### ISSUE TITLE
cron

### ISSUE THREAD

**Issue by cka3o4h1k** [tarampampam/nod32-update-mirror#39]
Почему-то скрипт не отрабатывает при запуске через cron. В логах крона есть
Запуск вручную нормально

**Comment by maximsource** [comment]
проверьте строки в crontab выше
скорее всего где-то там ошибка

**Comment by tarampampam** [comment]
К примеру, запись в кроне у меня имеет такой вид:
```bash
0 6,11,16,20 * * * /usr/bin/nice -n 19 /home/scripts/nod32upd/update.sh
```

**Comment by maximsource** [comment]
у меня так:
0 0 * * * root /var/nod32upd/update.sh

**Comment by alexspeedfire** [comment]
Вопрос к сказочнику: а у вас "полноценный" линух или роутер?
У меня на роутере была проблема c кроном:
скрипт отрабатывает из консоли (во всех скриптах первая строчка #!/opt/bin/bash), но через крон - пытался качать из updserver0 при включённой опции getfreekey. 
Перенаправив вывод скрипта в кронтабе в файл удалось увидеть следующее:
вызов getkey.sh сообщал об ошибке, wget ругался на неверные опции.
Проблема решилась (возможно*) следующим образом: в update.sh к вызовам bash и wget дописаны полные пути к "правильным" бинарникам (/opt/bin/bash и /opt/bin/wget)
Для wget - это 114 строка
для bash - 233.

Всякие подробности:
WL500gP v2, 1.9.2.7-rtn-r7440M-g736a62c
Linux version 2.6.22.21 (root@localhost) (gcc version 4.6.4 (GCC) ) #2 Thu Apr 21 02:25:31 MSK 2016
GNU bash, version 3.2.54(1)-release (mipsel-unknown-linux-gnu)
cron - 4.1-9 - Standard vixie cron, with cron.d addition
Строчка в кронтабе:
10 */6 * * * root /opt/usr/bin/nod32upd/update.sh

*возможно: точно скажу через 3 часа, сейчас работает с перенаправлением вывода. Чистый эксперимент будет при следующем запуске из кронтаба.

**Comment by cka3o4h1k** [comment]
Скрипт работает без костылей, например я не внимательно проверил конфиг.

Конкретнее, у меня крон запускается от admin, апдейтер размещен в папке /root, а в конфиге сабжа - дефолтный путь $home. 

Т.е. для меня из шелла $home в папке /root, но не для крона который работает из юзера admin
