### ISSUE TITLE
v9

### ISSUE THREAD

**Issue by GOSEF** [tarampampam/nod32-update-mirror#42]
Всем доброго времени!

Спешу поделиться наблюдением:
Изменил строку файла settings.cfg
`checkSubdirsList=('v4' 'v5' 'v6' 'v7' 'v8');`
на
`checkSubdirsList=('v4' 'v5' 'v6' 'v7' 'v8' 'v9');`

Смотрю, что-то качается в папку с обновлениями в подкаталог v9.

**Comment by tarampampam** [comment]
Думаете для девятой версии нода это является актуальным?

**Comment by GOSEF** [comment]
Я её даже не пробовал ставить. Но обновления там лежат же и качаются...

**Comment by tarampampam** [comment]
Принято, добавил. Спасибо!
