### ISSUE TITLE
1.0.1.6

### ISSUE THREAD

**Issue by mr-butch** [tarampampam/nod32-update-mirror#45]
1. Скрипт ругается на 25 строку, на readlink - "не верный параметр -e". Возможно у меня урезанный busybox. Возможно ли обойтись без этой команды?
2. Запускаю с --update, при закачке выдает красным "Downloading file error", хотя фактически файл загружается. Лог файл приложил.
[nod32mirror.txt](https://github.com/tarampampam/nod32-update-mirror/files/358026/nod32mirror.txt)

**Comment by tarampampam** [comment]
Пожалуйста, приложите всю информацию, которая [была запрошена](https://github.com/tarampampam/nod32-update-mirror/blob/master/.github/ISSUE_TEMPLATE.md) при создании issue. Без неё врятли чем-то смогу вам помочь.

**Comment by mr-butch** [comment]
Linux version 2.6.22.19 (root@asus) (gcc version 4.2.3) #1 Fri Jan 15 08:41:55 CST 2016

GNU bash, version 4.3.42(1)-release (mipsel-openwrt-linux-gnu)

GNU Wget 1.17.1 built on linux-gnu.
+digest -gpgme +https +ipv6 -iri +large-file -metalink -nls +ntlm
+opie -psl +ssl/openssl

curl 7.48.0 (mipsel-openwrt-linux-gnu) libcurl/7.48.0 OpenSSL/1.0.2h zlib/1.2.8
Protocols: file ftp ftps http https imap imaps pop3 pop3s rtsp smtp smtps tftp
Features: IPv6 Largefile SSL libz

cat: can't open './conf.d/*.conf': No such file or directory
export NOD32MIRROR_COLOR_OUTPUT=1;
export NOD32MIRROR_USE_FREE_KEY=1;
export NOD32MIRROR_MIRROR_DIR="/opt/etc/nod32-mirror/nod32mirror";
export NOD32MIRROR_TEMP_DIR="/opt/etc/nod32-mirror/nod32mirror/tmp";
export NOD32MIRROR_SERVER_0='http://update.eset.com:80/eset_upd/ username password';
export NOD32MIRROR_LANGUAGES='1033 1049';
export NOD32MIRROR_VERSIONS='pcu 4 5 6 7 8 9 10 11';
export NOD32MIRROR_LOG_PATH="/opt/etc/nod32-mirror/nod32mirror/nod32mirror.log";
export NOD32MIRROR_TEST_URI='http://update.eset.com:80/v8-rel-sta/mod_010_smon_1036/em010_32_l0.nup';
export NOD32MIRROR_TIMESTAMP_FILE_NAME='lastevent.txt';
export NOD32MIRROR_VERSION_FILE_NAME='version.txt';

**Comment by tarampampam** [comment]
Хорошо. По поводу первого - лучше всего скопируйте свой текущий конфиг в ./conf.d, и уже его изменяйте под себя (об этом было написано в readme-файле, но вам виднее конечно-же). Добавьте в него строку:
```bash
export NOD32MIRROR_BASE_DIR="/opt/etc/путь/до/директории/с_файлом_nod32-mirror.sh";
```

По поводу второго - попробуйте в конфиге выставить:
```bash
export NOD32MIRROR_CURL_BIN='false';
```

Тем самым заставив скрипт работать с **wget** вместо curl. Думаю, этого должно быть вполне достаточно.

**Comment by mr-butch** [comment]
По поводу первого, Еще со времен старых Ваших скриптов решаю этот вопрос заменой "dirname $(readlink -e $0)" на просто "dirname $0".  У меня только так работает.
Но все равно есть еще ошибки при выполнении:

# ./nod32-mirror.sh --update
./include/bootstrap.sh: line 61: id: command not found
[00:12:13] Please do not run this script as root
[Question] Do you want to continue? [y|n] y

Я отвечаю "y" и идет дальше, не знаю на что влияет это ошибка.

По поводу второго Ваше предложение помогло, теперь в конце строки "Download file..." пишет Success.

В остальном продолжаю тестировать.

**Comment by tarampampam** [comment]
`dirname $0` не сработает корректно, если к скрипту обращаться по симлинку. Но проблема известна, и именно поэтому пользуйтесь директивой `NOD32MIRROR_BASE_DIR`.

Попробуйте поработать с [cygwin](https://cygwin.com/install.html) (если стоит задача завести именно под windows), работа под ним протестирована и будет поддерживаться.

**Comment by mr-butch** [comment]
1. Строку:
export NOD32MIRROR_BASE_DIR="/opt/etc/путь/до/директории/с_файлом_nod32-mirror.sh";
добавлять в главный файл nod32-mirror.sh? В setting.conf не помогает.

2. На ошибку:
./include/bootstrap.sh: line 61: id: command not found
Не обращать внимания, и с ней все будет работать?

3. Для чего проверка на root права запуска? Как убрать сообщение о "Do you want to continue?" на вопрос о запуске из под root, у меня других учеток нет. Чтобы запускалось сразу без этих вопросов.

**Comment by tarampampam** [comment]
1. Как временное решение - можно просто изменить `[[ -z $NOD32MIRROR_BASE_DIR ]] && export NOD32MIRROR_BASE_DIR=$(dirname $(readlink -e $0));` в "nod32-mirror.sh" на `[[ -z $NOD32MIRROR_BASE_DIR ]] && export NOD32MIRROR_BASE_DIR="/opt/etc/путь/до/директории/с_файлом_nod32-mirror.sh";`, позже подумаю как этот костыль обойти.
2. Можно запускать с флагом `-f` - в этом случае ошибка проверки хоть и будет появляться, но значения никакого иметь не будет.
3. Это принципиальная ошибка, так как запускать скрипт, которому не нужны абсолютные права в системе под рутом - очень не правильно. Лучше завести отдельного пользователя, запереть его в рабочей директории, и из-под него производить запуск скрипта.

**Comment by mr-butch** [comment]
В чем отличие запуска скрипта вручную от запуска cron? 
Если скрипт запускать вручную, то по Вашему наводке изменив 
export NOD32MIRROR_CURL_BIN='false';
загрузка файлов пошла.
Но если же скрипт запускать через cron, то файлы закачиваться не хотят. Выходит ошибка загрузки. Формируются только папки с файлами update.ver. Самих файлов нет (

**Comment by tarampampam** [comment]
По идее разницы - никакой, если всё делается корректно. Без логов кронтаба, логов работы скрипта, отладочной информации и данных о запуске - ничего сказать не могу. Пора бы это уже понять.

**Comment by mr-butch** [comment]
Теперь разобрался, в файле nod32keys.sh нужно было заменить переменную $HOME на нужный мне путь сохранения ключей. Считаю необходимым вынести в конфигурационный файл путь сохранения ключей, либо NOD32MIRROR_BASE_DIR, потому как $HOME у меня лично не срабатывает.

**Comment by tarampampam** [comment]
Достаточно в конфиг добавить:
```bash
export NOD32MIRROR_KEYS_DIRECTORY="$HOME/.nod32keys";
```

Но ваше замечание по поводу выноса данной опции в конфиг я обязательно учту, спасибо!

**Comment by mr-butch** [comment]
1. В общем с этим новым скриптом таже самая проблема как и со старым. Если файлы в папке nod32mirror есть, пишет "Downloading file error", если папку очистить - "Success". Чуда не произошло (( Или это так задумано (хотя я бы при существующем файле что то типа Skipped выводил, имхо)
2. Не обновляются клиенты, пишет в ошибке "Файл не найден". Тогда как файл существует, но ищется почему то в корне сервера. Заметил что прежний скрипт формировал путь до файла как "file=xxx.nup", тогда как новый "file=/xxx.nup". Возможно в слеше проблема, что в моем случае не находит? Возможно ли его мне убрать при формировании update.ver файла ?

**Comment by tarampampam** [comment]
Без конфигов как скрипта, так и nginx, без лога, без описания действия для воспроизведения поведения - увы, помочь ничем не могу.

**Comment by mr-butch** [comment]
Я не уверен что там вообще nginx, загружаю на внешний. 

Конфиг снова приложил, его не менял.
[default.txt](https://github.com/tarampampam/nod32-update-mirror/files/368441/default.txt)

У меня обновления лежат в папке NodUpDate, поэтому с прежним скриптом клиенты обращаются:

[13/Jul/2016:06:00:15 +0300] "GET /NodUpDate/em001_32_l0.nup HTTP/1.0" 200 764793 "-" "ESS Update (Windows; U; 32bit......)" 

С новым скриптом обращение идет на:

[18/Jul/2016:09:09:05 +0300] "GET /em017_64_l0.nup HTTP/1.1" 404 304 "-" "ESS Update (Windows; U; 32bit....)"

и соответственно файлы не находит.  Если залить обновления сформированные старым скриптом, то все ОК, клиенты обновляются.

**Comment by mr-butch** [comment]
А по поводу 1-го вопроса, у Вас все ок, при уже имеющихся файлах в папке nod32mirror?

**Comment by tarampampam** [comment]
К сожалению, я буду вынужден повторить то что уже говорил ранее:
 1. Если прикладываете конфиг - то прикладывайте его содержание согласно [примеру](https://github.com/tarampampam/nod32-update-mirror/blob/master/.github/ISSUE_TEMPLATE.md) (там же указано и как его оформить, и как получить);
 2. Прочитайте условия работы скрипта в [readme файле](https://github.com/tarampampam/nod32-update-mirror/blob/master/README.md) - обязательным условием эксплуатации является ___корректно настроенный___ `nginx`:
 3. По поводу пути - есть директива `NOD32MIRROR_URI_PATH`. Перед тем как задавать свой вопрос, ознакомьтесь внимательнее с возможными настройками, пожалуйста;
 4. Если текущая версия для вас является столь сложной в настройке - [используйте старую версию](https://github.com/tarampampam/nod32-update-mirror/tree/b749300740dda68f075cd9b5da3282fb2be475a3). Почему было принято решение переписать скрипт указано в [changeslog](https://github.com/tarampampam/nod32-update-mirror/blob/master/CHANGESLOG.md).

**Comment by mr-butch** [comment]
Прошу прощения, собрал все в одно сообщение.

Шаги для воспроизведения проблемы (steps to reproduce):
1. Первый запуск nod32-mirror с параметром -u. Папки nod32mirror не существует или пуста.

Что произошло на самом деле (actual behaviour):
1. Произошло ожидаемое - скачались файлы обновлений без ошибок.

Linux version 2.6.22.19 (root@asus) (gcc version 4.2.3) #1 Fri Jan 15 08:41:55 CST 2016

GNU bash, version 4.3.42(1)-release (mipsel-openwrt-linux-gnu)

GNU Wget 1.17.1 built on linux-gnu.
+digest -gpgme +https +ipv6 -iri +large-file -metalink -nls +ntlm
+opie -psl +ssl/openssl

curl 7.48.0 (mipsel-openwrt-linux-gnu) libcurl/7.48.0 OpenSSL/1.0.2h zlib/1.2.8
Protocols: file ftp ftps http https imap imaps pop3 pop3s rtsp smtp smtps tftp
Features: IPv6 Largefile SSL libz

Выход команды cat ./settings.conf ./conf.d/*.conf | grep -v -e '^#' -e '^$':

export NOD32MIRROR_MIRROR_DIR="$HOME/nod32mirror";
export NOD32MIRROR_SERVER_0='http://update.eset.com:80/eset_upd/ username password';
export NOD32MIRROR_SERVER_1='http://nod32.someserver.com/';
export NOD32MIRROR_SERVER_2='http://someserver2.com/nod32/';
export NOD32MIRROR_LANGUAGES='1033 1049';
export NOD32MIRROR_CURL_BIN='false';
export NOD32MIRROR_TEST_URI='http://update.eset.com:80/v8-rel-sta/mod_010_smon_1036/em010_32_l0.nup';
export NOD32MIRROR_TIMESTAMP_FILE_NAME='lastevent.txt';
export NOD32MIRROR_VERSION_FILE_NAME='version.txt';
export NOD32MIRROR_COLOR_OUTPUT=1;
export NOD32MIRROR_USE_FREE_KEY=1;
export NOD32MIRROR_MIRROR_DIR="/opt/etc/nod32-mirror/nod32mirror";
export NOD32MIRROR_TEMP_DIR="/opt/etc/nod32-mirror/tmp";
export NOD32MIRROR_URI_PATH='NodUpDate';
export NOD32MIRROR_SERVER_0='http://update.eset.com:80/eset_upd/ username password';
export NOD32MIRROR_LANGUAGES='1033 1049';
export NOD32MIRROR_LOG_PATH="/opt/etc/nod32-mirror/.nod32keys/nod32mirror.log";
export NOD32MIRROR_TEST_URI='http://update.eset.com:80/v8-rel-sta/mod_010_smon_1036/em010_32_l0.nup';
export NOD32MIRROR_TIMESTAMP_FILE_NAME='lastevent.txt';
export NOD32MIRROR_VERSION_FILE_NAME='version.txt';

log работы скрипта и то что выводится на экран:

[nod32mirror.log.txt](https://github.com/tarampampam/nod32-update-mirror/files/368817/nod32mirror.log.txt)
[16.07.18-12.30.txt](https://github.com/tarampampam/nod32-update-mirror/files/368819/16.07.18-12.30.txt)

2. Запускаем скрипт повторно, Папки nod32mirror при этом существует и НЕ пуста.

Какое действие ожидалось (expected behaviour):
2. Ожидалось закачка обновленных файлов, или тех которых не существует.

Что произошло на самом деле (actual behaviour):
2. На уже существующие файлы выводятся сообщения "Downloading file error".

Для отчета добавил в conf файл export NOD32MIRROR_DEBUG_MODE=1;

log работы скрипта и то что выводится на экран:

[nod32mirror.log.txt](https://github.com/tarampampam/nod32-update-mirror/files/368976/nod32mirror.log.txt)
[16.07.18-14.45.txt](https://github.com/tarampampam/nod32-update-mirror/files/368978/16.07.18-14.45.txt)

Сообщения в log файле - Successfully downloaded files: 0, skipped: 0, with errors: 88.
