### ISSUE TITLE
Невозможно получить бесплатные ключи

### ISSUE THREAD

**Issue by 1nn0** [tarampampam/nod32-update-mirror#48]
#### Шаги для воспроизведения проблемы *(steps to reproduce)*
 1.  ./nod32-mirror.sh -k
 

#### Какое действие ожидалось *(expected behaviour)*
Видимо, получение ключей из заданных источников.

#### Что произошло на самом деле *(actual behaviour)*

```
[Debug   ] Execute "get key" action

Use for educational or informational purposes only!

[Debug   ] Returned random key is
[Debug   ] Removeing invalid keys failed: valid keys file not found
[09:28:38] Requesting for a new free keys..
[09:28:38] Cannot get new free keys :(
[Debug   ] Returned random key is
Fatal error: Cannot get valid free key

```

---------

#### Данные системы *(system information)*
**Операционная система (operating system)**:
```
Linux version 2.6.32-openvz-042stab113.11-amd64
```

**Bash**:
```bash
GNU bash, version 4.2.37(1)-release (i486-pc-linux-gnu)
```

**wget / curl**:
```bash
$ wget -V
GNU Wget 1.13.4 built on linux-gnu
$ curl -V
curl 7.26.0 (i486-pc-linux-gnu) libcurl/7.26.0 OpenSSL/1.0.1e zlib/1.2.7 libidn/1.25 libssh2/1.4.2 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: Debug GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

---------

#### Настройки (settings):
**Настройки скрипта (script settings)**:
```bash
$ cat ./settings.conf ./conf.d/*.conf | grep -v -e '^#' -e '^$'
```
```shell
export NOD32MIRROR_DEBUG_MODE=1;
export NOD32MIRROR_MIRROR_DIR="/var/www";
export NOD32MIRROR_SERVER_0='http://update.eset.com:80/eset_upd/ username password';
export NOD32MIRROR_SERVER_1='http://biysk.pro/nod/';
export NOD32MIRROR_LANGUAGES='1033 1049';
export NOD32MIRROR_LOG_PATH="$HOME/nod32mirror.log";
export NOD32MIRROR_CURL_BIN='false';
export NOD32MIRROR_TEST_URI='http://update.eset.com:80/v8-rel-sta/mod_010_smon_1036/em010_32_l0.nup';
export NOD32MIRROR_TIMESTAMP_FILE_NAME='lastevent.txt';
export NOD32MIRROR_VERSION_FILE_NAME='version.txt';

...
```

**Лог-файл (log-file):**
нет лога.

**Comment by 1nn0** [comment]
Хмм, скрипт автоматически не нашел ни curl (очевидно, ведь он отключен) ни wget. Стоило прописать вручную - все взлетело.

**Comment by kasumiru** [comment]
Подтверждаю данную особенность, что в сабже! 
Был и curl и wget, ос дебиан. При запуске ./nod32-mirror.sh -k выдавало тоже самое: 
[Debug   ] Returned random key is
Fatal error: Cannot get valid free key
По совету 1nn0 выставил в файле settings.conf принудительно 
export NOD32MIRROR_CURL_BIN='/usr/bin/curl';
после чего скрипт стал работать. Есть предложение добавить что то вроде `/usr/bin/which curl` в конфиг файл.
