### ISSUE TITLE
Скрипт не находит бесплатные ключи для проверки работы скрипта

### ISSUE THREAD

**Issue by RavenHuginn** [tarampampam/nod32-update-mirror#49]
#### Какое действие ожидалось *(expected behaviour)*

Поиск бесплатного ключа для тестирования работы скрипта

#### Что произошло на самом деле *(actual behaviour)*

Скрипт не ищет ключи

---------

#### Данные системы *(system information)*
**Операционная система (operating system)**:
```bash
$ cat /proc/version
Linux version 3.13.0-32-generic (buildd@toyol) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #57~precise1-Ubuntu SMP Tue Jul 15 03:50:54 UTC 2014

```

**Bash**:
```bash
$ bash --version
GNU bash, version 4.2.25(1)-release (i686-pc-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```

**wget / curl**:
```bash
$ wget -V
GNU Wget 1.13.4 built on linux-gnu.
$ curl -V
curl 7.22.0 (i686-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
```

---------

#### Настройки (settings):
**Настройки скрипта (script settings)**:
```bash
$ cat ./settings.conf ./conf.d/*.conf | grep -v -e '^#' -e '^$'
export NOD32MIRROR_COLOR_OUTPUT=1;
export NOD32MIRROR_USE_FREE_KEY=1;
export NOD32MIRROR_MIRROR_DIR="/usr/share/nginx/nod32mirror";
export NOD32MIRROR_SERVER_0='http://update.eset.com:80/eset_upd/ username password';
export NOD32MIRROR_SERVER_1='http://nod32.someserver.com/';
export NOD32MIRROR_SERVER_2='http://someserver2.com/nod32/';
export NOD32MIRROR_LANGUAGES='1033 1049';
export NOD32MIRROR_VERSIONS='pcu 4 5 6';
export NOD32MIRROR_LOG_PATH="$HOME/nod32mirror.log";
export NOD32MIRROR_CURL_BIN='false';
export NOD32MIRROR_TEST_URI='http://update.eset.com:80/v8-rel-sta/mod_010_smon_1036/em010_32_l0.nup';
export NOD32MIRROR_TIMESTAMP_FILE_NAME='lastevent.txt';
export NOD32MIRROR_VERSION_FILE_NAME='version.txt';

```
```shell
export NOD32MIRROR_DEBUG_MODE=0;
export NOD32MIRROR_COLOR_OUTPUT=1;
export NOD32MIRROR_USE_FREE_KEY=0;
...
```

**Лог-файл (log-file):**
```bash
$ cat ./nod32mirror.log | tail -n 30
[2016-08-10/22:18:38] [Info] Requesting for a new free keys..
[2016-08-10/22:18:39] [Error] Cannot get new free keys :(
[2016-08-10/22:18:40] [FATAL ERROR] Cannot get valid free key

```
```log
[YYYY-MM-DD/HH:MM:SS] [Type] Some log message.. 
...
```

**Comment by tarampampam** [comment]
Так, давай изменим `export NOD32MIRROR_DEBUG_MODE=1;`, запустим `./nod32-mirror.sh -k` и посмотрим на вывод

**Comment by RavenHuginn** [comment]
[2016-08-10/22:50:02] [Debug] Execute "get key" action
[2016-08-10/22:50:03] [Debug] Returned random key is
[2016-08-10/22:50:04] [Debug] Removeing invalid keys failed: valid keys file not found
[2016-08-10/22:50:04] [Info] Requesting for a new free keys..
[2016-08-10/22:50:06] [Error] Cannot get new free keys :(
[2016-08-10/22:50:07] [Debug] Returned random key is
[2016-08-10/22:50:07] [FATAL ERROR] Cannot get valid free key

**Comment by RavenHuginn** [comment]
если в папке со скриптом создать папку .nod32keys и в ней файл validkeys.txt а туда вписать логин:пароль то начинает работать. А сам скрипт не ищет сайтах новые ключи

**Comment by tarampampam** [comment]
* Каков полный путь до директории `nod32-mirror`?
* Есть ли права на запись в домашнюю директорию?
* Существует ли директория `$HOME/.nod32keys`, и если да - то какие права на неё и какое её содержимое?
* Есть ли права на запись в `/tmp`?

Кажется, к вас что-то не так именно с правами.

**Comment by RavenHuginn** [comment]
У меня создан пользователь nod32upd. Скрипт лежит в папке /home/nod32upd/. Директории .nod32keys по умолчанию нет, создавал сам права 775 владелец nod32upd из под этого пользователя и запускаю скрипт. Права на /tmp 777

**Comment by tarampampam** [comment]
Попробуйте выполнить под привилегированным пользователем выполнить:
```bash
$ sudo -u nod32upd echo "$HOME"
```

Что покажет?

**Comment by RavenHuginn** [comment]
Ладно не работает и фиг с ним. Главное я разобрался как вручную подсунуть ключ. Позже попробую всё настроить для привилегированного пользователя. И попробую установить на CentOS. Спасибо за беспокойство.

**Comment by tarampampam** [comment]
Постойте. Для того чтоб обновляться с помощью постоянного ключа достаточно его указать просто в настройках, установив `export NOD32MIRROR_USE_FREE_KEY=0`. Если запускать из под "обычного" пользователя - всё работает как надо?

**Comment by RavenHuginn** [comment]
как то так? 
export NOD32MIRROR_SERVER_0='http://update.eset.com:80/eset_upd/ TRIAL-0173353607 undderubvt';
Вроде скачиваются файлы обновлений, сейчас оставлю на ночь посмотрю что выйдет

**Comment by tarampampam** [comment]
Да, именно. Держите меня в курсе если будут какие-либо проблемы. Закрываю.
