### ISSUE TITLE
Файл поврежден

### ISSUE THREAD

**Issue by volde-mar** [tarampampam/nod32-update-mirror#53]
## Шаги для воспроизведения проблемы (steps to reproduce)
1. Запуск скрипта
## Какое действие ожидалось _(expected behaviour)_

Выполнение скрипта и обновление Nod32 v8
## Что произошло на самом деле _(actual behaviour)_

Получаю сообщение "Файл поврежден" после попытки обновления Nod32 v8 (кэш обновлений антивируса очищал)

Ранее пользовался вашими скриптами - проблем не возникало, в роли http сервера использовал lighttpd без анализа user-agent, есть ли в анализе user-agent большая необходимость в этой версии скрипта? Сейчас использую nginx как вы рекомендуете. Не до конца понятно как происходит обновление антивируса с зеркала, достаточно ли ткнуть антивирус в корень веб сервера в этой версии скрипта для корректного обновления? Поясните пожалуйста если не сложно 

---
### Данные системы _(system information)_

**Операционная система (operating system)**:

``` shell
$ cat /proc/version
Linux version 4.1.23 (vadim@compille) (gcc version 5.3.0 (OpenWrt GCC 5.3.0 r49395) ) #2 Sat Aug 20 07:37:51 UTC 2016
```

**Bash**:

``` shell
$ bash --version
GNU bash, version 4.3.42(1)-release (mips-openwrt-linux-gnu)
```

**wget / curl**:

``` shell
$ wget -V
GNU Wget 1.18 built on linux-gnu.
-cares +digest -gpgme +https -ipv6 -iri +large-file -metalink -nls
+ntlm +opie -psl +ssl/openssl


$ curl -V
curl 7.48.0 (mips-openwrt-linux-gnu) libcurl/7.48.0 mbedTLS/1.3.16
Protocols: file ftp ftps http https
Features: Largefile SSL
```

---
### Настройки (settings):

**Настройки скрипта (script settings)**:

``` shell
$ cat ./settings.conf ./conf.d/*.conf | grep -v -e '^#' -e '^$'

export NOD32MIRROR_MIRROR_DIR="$HOME/nod32mirror";
export NOD32MIRROR_SERVER_0='http://update.eset.com:80/eset_upd/ username password';
export NOD32MIRROR_SERVER_1='http://nod32.someserver.com/';
export NOD32MIRROR_SERVER_2='http://someserver2.com/nod32/';
export NOD32MIRROR_LANGUAGES='1033 1049';
export NOD32MIRROR_CURL_BIN='false';
export NOD32MIRROR_TEST_URI='http://update.eset.com:80/v8-rel-sta/mod_010_smon_1036/em010_32_l0.nup';
between downloading files (numeric, in seconds)
export NOD32MIRROR_TIMESTAMP_FILE_NAME='lastevent.txt';
export NOD32MIRROR_VERSION_FILE_NAME='version.txt';
export NOD32MIRROR_USE_FREE_KEY=1;
export NOD32MIRROR_MIRROR_DIR="/share/public/wwweset/webroot/eset";
export NOD32MIRROR_TEMP_DIR="/share/public/wwweset/webroot/eset/.tmp";
export NOD32MIRROR_URI_PATH='eset';
export NOD32MIRROR_SERVER_0='http://update.eset.com:80/eset_upd/ username password';
export NOD32MIRROR_SERVER_1='http://nod32.someserver.com/';
export NOD32MIRROR_SERVER_2='http://someserver2.com/nod32/';
export NOD32MIRROR_LANGUAGES='1049';
export NOD32MIRROR_VERSIONS='8';
export NOD32MIRROR_LOG_PATH="/share/log/nod32mirror.log";
export NOD32MIRROR_CURL_BIN='false';
export NOD32MIRROR_TEST_URI='http://update.eset.com:80/v8-rel-sta/mod_010_smon_1036/em010_32_l0.nup';
export NOD32MIRROR_TIMESTAMP_FILE_NAME='lastevent.txt';
export NOD32MIRROR_VERSION_FILE_NAME='version.txt';
```

<details> 
<summary>

**Отладочный-лог / Вывод работы скрипта (debug-log)**:</summary>

``` log


```

[nod32mirror.txt](https://github.com/tarampampam/nod32-update-mirror/files/441333/nod32mirror.txt)

</details>

**Comment by tarampampam** [comment]
Да, для новой версии использование nginx обязательно. Если использовать другой веб-сервер - то клиенты будут получать не совсем корректные обновления. Работать будет, конечно, но не так как надо - без гарантии того что eset nod32 пятой версии получит обновления именно для пятой версии.

Можно антивирусу ткнуть просто в корень зеркала (_без указания под-директории вида `/v%num%/`_) - для этого собственно он то и нужен (_смотрите пример его конфига - всё должно быть понятно_).

Что бы я вам советовал попробовать:
1. Выяснить что за строка в конфиге `between downloading files (numeric, in seconds)`, и как она попала в выдачу ката;
2. "Завести" зеркало именно на отдельном домене, без использования "вложенной" директории (как минимум - на время отладки, так как так будет и проще, и на одну точку отказа меньше), для чего закомментируйте `NOD32MIRROR_URI_PATH` и в `NOD32MIRROR_MIRROR_DIR` выставите `/share/public/wwweset/webroot`;
3. Приложить лог в развернутом виде, а не ссылкой на файл. К сожалению - нет никакого желания в нем копаться где то ещё, кроме как здесь;
4. Приложить последовательность команд, которые вы выполняете, и собственно лог того, что выводится в консоли.

Если необходимо завести зеркало только для одной версии антивируса - то можно заюзать и `lighttpd`, для чего сперва добиться корректной работы скрипта, а после в качестве вебрута указать именно ту под-директорию, в которой содержатся обновления необходимой версии.

**Comment by volde-mar** [comment]
То есть этим куском конфига nginx:

# Redirect request to correct update.ver file, based on nod32 user-agent version
  location ~* "^(?<file_url>/update\.ver)$" {
    if ($http_user_agent ~* "BPC (?<version>[\d]{1,2})\.") {
      set $new_location "v$version$file_url";
    }
    if (-f $document_root/$new_location) {
      return 301 $scheme://$server_name/$new_location;
    }
}

мы говорим ноду версии 5 брать файлы обновления из папки v5 ?

 Для чего используются файлы обновлений не распределенные в папки v%num% (находящиеся в корне)

Про это "between downloading files (numeric, in seconds)" проверю

По проблеме удалось выяснить что проблема на уровне железа в частности hdd подцепленного по usb. В директории оказались файлы не видимые при ls -l а при попытке удаления получал сообщения о существовании файлов em01 em02. Выяснилось что hdd сыпется, заменил на другой пока полет нормальный, за исключением сообщений **Downloading file error** при обновлениях уже скачанных файлов (обсуждается в тикете 1.0.1.8 ). В старых версиях скрипта была такая проблема, в скрипте просто добавил skipped на ответ wget, здесь пока не известно как это сделать.
Проверю будет ли обновляться зеркало при получении этих сообщений.

**Comment by tarampampam** [comment]
> мы говорим ноду версии 5 брать файлы обновления из папки v5 ?

Да, именно.

> Для чего используются файлы обновлений не распределенные в папки v%num% (находящиеся в корне)

Да вот хер знает. Документации по официальному зеркалу же нет никакой, всё делалось "на ощупь" да с помощью проксирования запросов и их разбором. Так как при запросе в корне файлы есть - их я решил тоже зеркалить.

> за исключением сообщений Downloading file error при обновлениях уже скачанных файлов 

Да, проблема известная, но пока ручки не доходят чтоб всё пофиксить.

Как проверишь всё - дай знать, пожалуйста.

**Comment by volde-mar** [comment]
Для проверки понадобиться несколько дней, о результатах отпишу в этом тиките, пока не закрывайте.

**Comment by tarampampam** [comment]
Да, разумеется :+1:

**Comment by volde-mar** [comment]
Да и еще если я пропишу в nod в настройках обновления http://%адрес сервера%/v5 то по сути антивирус должен обновиться "своими" правильными обновлениями. При использовании ваших скриптов ранее ноду указывал только http://%адрес сервера% и все прекрасно обновлялось

**Comment by tarampampam** [comment]
Только потому, что раньше по факту все под-директории вида `vN` попросту не использовались :)
В текущей версии работа построена правильнее. А так как править старую версию на новый лад совсем не тривиально - всё и было переписано с нуля.

**Comment by volde-mar** [comment]
Ясно, протестируем

**Comment by tarampampam** [comment]
Ну как?

**Comment by volde-mar** [comment]
1. К сожалению накатить версию 1.0.1.8 не успел, поскольку использую лайти а для тестового использования nginx нужно было пересобрать прошивку, что сегодня было сделано, вечером накачу, и проверю. Сейчас стоит версия 1.0.0.1 и корректно работает на мой взгляд.
2. Планирую использовать по прежнему лайти. Поскольку убедился что действительно nod v5 из корня не обновляется как например nod v8. В лайти же реврайт по юзер агенту на необходимый подкаталог работает корректно.
3. Лифтинг поправлял и в 1.0.0.1 и в 1.0.1.8 добавив ответ wgeta в варианты для skipped

**Comment by volde-mar** [comment]
и еще интересно, как антивирус забирает обновы из /pcu?

**Comment by tarampampam** [comment]
Полагаю, что самостоятельно запрашивает, если в настройках стоит опция "Обновлять программные компоненты", но до полноценного теста не дошло - желание ковыряться с отладчиком не бесконечно
