### ISSUE TITLE
Eset 10 update

### ISSUE THREAD

**Issue by server801** [tarampampam/nod32-update-mirror#56]
Здравствуйте! Отличный проект , скрипт работает отлично. Но меня интересует 10 версия антивируса. Есть несколько вопросов 
1. работать хочет только по ссылке http://nod.ru/eset_upd/v10/dll/ , реврайт тут не катит, nginx 10 версию не хочет понимать как юзер агента ..
2. Нод 10 версии ищет файл /v10-dll-rel-sta/mod_002_engine_31454/**em002_64_n1.dll.nup**, его нет , а есть только без dll посередине - **em002_64_n1.nup**
3. Есть на  перле написанный скрипт работает только для 7, 8 версии . 10 вообще не хочет , update.ver качает , но что то не поймет он что дальше ему делать . Попробовал ваш вариант , по сути тоже самое, качает директории с обновами , но с них не хочет обновляться. 
Рассматриваете в будущем или уже в настоящем модернизацию скрипта под 10 версию?

**Comment by server801** [comment]
Еще заметил  
Запускаю с лицензионным ключем от нод 32 для домашнего использования, не  ESS, при обновлении скрипт отказывается качать некоторые файлы 
`[10:05:39] Download file "http://update.eset.com:80/v3-rel-sta/mod_021_horus_8971/em021_32_l1.nup" (59 of 79).. Downloading file error
[10:05:40] Download file "http://update.eset.com:80/v3-rel-sta/mod_021_horus_8979/em021_32_l2.nup" (60 of 79).. Downloading file error`
А если запустить с триальными ключами , который скрипт ищет сам , то все ок
`[10:09:39] Download file "http://update.eset.com:80/v3-rel-sta/mod_021_horus_8971/em021_32_l1.nup" (59 of 79).. Success
[10:09:40] Download file "http://update.eset.com:80/v3-rel-sta/mod_021_horus_8979/em021_32_l2.nup" (60 of 79).. Success`

Так должно быть?

**Comment by tarampampam** [comment]
Десятая и подобные версии требуют отдельной лицензии, или я ошибаюсь?

Для проверки - попробуйте скачать тот же файл браузером, введя в окне авторизации свои логин:пароль - качается успешно? По идее, разницы не должно быть между тестовыми и приобретенными ключами

**Comment by server801** [comment]
Нет, ключи для 10 версии те же, без разницы  Причем можно использовать ключ от ess , к eav обновы подходят. А вот наоборот не пробовал . 
Необходимо понять, почему 10 версия ищет ищет файл с dll посередине : file.dll.nup . 
Кстати ,пробовал запустить скрипт на freebsd, не завелся. А очень бы хотелось...

**Comment by tarampampam** [comment]
По поводу dll посередине - думаю, есть смысл скачать ручками файл update.ver, распаковать его, и глянуть на содержимое. Используя при этом соответствующую пару логин:пароль, разумеется. Раньше по крайней мере таких записей в нем не встречал.

По поводу запуска на freebsd создайте лучше отдельный тикет, корректно его оформив. Попробуем разобраться.

**Comment by server801** [comment]
В том то и дело что нет таких записей в update.ver ))) а нод с офф зеркал тянет именно эти файлы )) распакую - проверю , отпишусь.

**Comment by server801** [comment]
Нашел )) 
Адреса  

`Other=10@http://um02.eset.com/eset_upd/v10/dll/, 10@http://91.228.166.13/eset_upd/v10/dll/, 10@http://um03.eset.com/eset_upd/v10/dll/, 10@http://91.228.166.16/eset_upd/v10/dll/, 10@http://um05.eset.com/eset_upd/v10/dll/, 10@http://91.228.167.133/eset_upd/v10/dll/, 10@http://um07.eset.com/eset_upd/v10/dll/, 10@http://38.90.226.37/eset_upd/v10/dll/, 10@http://um09.eset.com/eset_upd/v10/dll/, 10@http://38.90.226.39/eset_upd/v10/dll/, 10@http://um11.eset.com/eset_upd/v10/dll/, 10@http://38.90.226.40/eset_upd/v10/dll/, 10@http://um21.eset.com/eset_upd/v10/dll/, 10@http://91.228.167.21/eset_upd/v10/dll/, 100000@http://update.eset.com/eset_upd/v10/dll/
`
Файлы 

`file=/v10-dll-rel-sta/mod_000_nativeloader_km_1010/em000k_64_l0.dll.nup
file=/v10-dll-rel-sta/mod_000_nativeloader_km_1010/em000k_32_l0.dll.nup
и т.д
`
Прикрепил файл 


[eset.txt](https://github.com/tarampampam/nod32-update-mirror/files/630767/eset.txt)

**Comment by server801** [comment]
```
547M    ./v10-dll-pre-sta
358M    ./v10-dll-rel-def
571M    ./v10-dll-rel-sta
574M    ./v10-rel-sta

```
Вот такие директории теперь есть для 10 нода. Качаю перловым скриптом.  Нод в упор не хочет обновляться с этих папок. Похоже иерархия обновлений для 10 версии  поменяна на другой алгоритм. И видимо настройки для nginx есть особые. Нужно копать в этом направлении.
