### ISSUE TITLE
Need a option change eset official update site

### ISSUE THREAD

**Issue by cnzzr** [tarampampam/nod32-update-mirror#61]
for example change 
export NOD32MIRROR_SERVER_URI='http://update.eset.com:80/eset_upd/';
to locale proxy update site by settings.conf.

http://u7.eset.com.cn/eset_upd/ 

ths.

**Comment by tarampampam** [comment]
You can set **any** mirror server URI [here](https://github.com/tarampampam/nod32-update-mirror/blob/master/nod32-mirror/settings.conf#L47), or you needed anything another?
