### ISSUE TITLE
Nginx config

### ISSUE THREAD

**Issue by alegzz** [tarampampam/nod32-update-mirror#62]
41 строка
 return 301 $scheme://$server_name/$new_location;
следует изменить на
 return 301 $scheme://$host/$new_location;
иначе не будет работать, если не указан server_name

**Comment by tarampampam** [comment]
Можете оформить в виде PR с дополнительным `if`, чекающим данный кейс?

**Comment by alegzz** [comment]
Зачем? Достаточно изменить как я написал. Из описанного ниже следует, что это самый правильный вариант 
$host contains "in this order of precedence: host name from the request line, or host name from the 'Host' request header field, or the server name matching a request"
$http_host contains the content of the HTTP "Host" header field, if it was present in the request
$server_name contains the server_name of the virtual host which processed the request, as it was defined in the nginx configuration. If a server contains multiple server_names, only the first one will be present in this variable.

**Comment by mr-butch** [comment]
Добрый день.
Подскажите пожалуйста, не обновляется 5-я версия Нода. Остальные обновляются корректно. Для того чтобы обновлялась и 5-я, нужно явно указывать - "http://ip/v5/", хотя остальным для обновления достаточно и "http://ip/". В настройках nginx есть абзац для редиректа, основанного на user-agent.

Вид:
 location ~* "^(?<file_url>/update\.ver)$" {
    if ($http_user_agent ~* "BPC (?<version>[\d]{1,2,5})\.") {
      set $new_location "v$version$file_url";
    }
    if (-f $document_root/$new_location) {
      return 301 $scheme://ip/$new_location;
    }
  } 
не дает результата.

Подскажите пожалуйста, как правильно его настроить?
