### ISSUE TITLE
Скачивание самих файлов с третьего сайта

### ISSUE THREAD

**Issue by mr-butch** [tarampampam/nod32-update-mirror#65]
Добрый день.
Возможно ли настроить скрипт формирования update.ver так, чтобы сами файлы находились на третьем сайте, То есть по адресу www.domain.ru\update.ver указывает на необходимые файлы, которые расположены по www.domain1.ru\*.nup?
Есть параметр URI_PATH в котором можно указать директорию того же сайта, в котором брать сами файлы. Будет ли это работать с совершенно другим сервером? Как настроить для этого случая?
С уважением.

**Comment by mr-butch** [comment]
tarampampam, бываешь здесь?
Можно ли в URI_PATH указать вместо nod32mirror_uri_path='nodupdate' указать к примеру 'server1.ru/nodupdate'?
То есть сам файл version лежит на одном серваке, а файлы обновления на другом?

**Comment by tarampampam** [comment]
Привет, бываю, но не так часто, как хотелось бы.

По идее - должно работать, попробуй.
