### ISSUE TITLE
зависание при скачке

### ISSUE THREAD

**Issue by moobi08** [tarampampam/nod32-update-mirror#66]
доброго времени суток. вообщем поставил я ваш скрипт на дебиан. все запускается но есть один нюанс. к примеру запускаеш первый раз с норм лицензией начинает качать обновления потом  на скачке какого то по номеру останавливается и дальше не идет. приходится перезапускать обновление и так  потихоньку продвигаясь. но это морока жесть. может параметр какойто мешает7 подскажите куда капнуть) спасибо

**Comment by moobi08** [comment]
вот так это выглядит.[23:22:01] Download file "http://update.eset.com:80/v3-rel-sta/mod_003_archives_1338/em003_32_l1.nup" (10 of 85).. Success
[23:22:02] Download file "http://update.eset.com:80/v3-rel-sta/mod_004_advheur_1154/em004_32_l0.nup" (11 of 85)..
 сейчас перезапущу и оно скачает 11 и пойдет дальше пока снова не споткнется на чем то

**Comment by moobi08** [comment]
победил это. теперь нод при обновлении говорит файл на сервере не найден

**Comment by MasterSoft24** [comment]
@moobi08 , a как победил?

**Comment by moobi08** [comment]
да сменил ип сервера с внешнего на внутренне локальный

**Comment by Digitint** [comment]
Та же проблема. Углубился. Зависает на старых файлах которые стягиваются с официального сервера ESET.  Например http://update.eset.com/v3-rel-sta/mod_002_engine_30152/em002_32_l0.nup - изменен 19.07.2016. Вручную, через wget иногда тот же файл скачивает, а иногда скорость падает до 0 и загрузка также подвисает. Думаю проблема бы решилась если в конфиге сделать дополнительную переменную для исключений по маске файла и прописать там файлы на которых подвисает загрузка и таким образом просто-напросто их игнорировать. Кстати, их можно перекачать и загрузить на зеркало вручную. При скачке с неофициальных серверов или местного RA, проблема не наблюдалась.
