### ISSUE TITLE
Error updating EAV 12

### ISSUE THREAD

**Issue by starhobbit** [tarampampam/nod32-update-mirror#79]
Не обновляется, ругается на некорректную ссылку. Диагностика показала, что если в файл /v12/dll/update.ver в HOSTS вписать сервер, а в файлах писать только путь, то всё работает. Возможно, если Вы раньше не сделаете, сделаю пулл-реквест

**Comment by starhobbit** [comment]
что-то и 8я у меня обновляться отказалась без этого исправления...

**Comment by starhobbit** [comment]
мой косяк - не поправил конфиги при переезде на новую версию... в переменной адрес был написан, а нужен путь (или ни чего, если в корне)

**Comment by server801** [comment]
> мой косяк - не поправил конфиги при переезде на новую версию... в переменной адрес был написан, а нужен путь (или ни чего, если в корне)

А как вы настроили клиент v12 ? Расскажите?

**Comment by starhobbit** [comment]
поставил в реестре f5ac (62892), НО после апдейта с зеркала срок лицензии не сбросился... стоит на виртуалке, посмотрю что случится, когда срок лицензии кончится

**Comment by starhobbit** [comment]
Не работает облачный антивирь, остальное в 12м работает со  своим зеркалом и инструкцией выше, чтоб не орал - можно в настройках интерфейса антивиря снять галку с гварда, когда он отключён

**Comment by starhobbit** [comment]
поторопился... 05.06 кончается лицензия - облако отвалилось, т.к. ключ забанили...
