### ISSUE TITLE
Мануал по установке и запуску

### ISSUE THREAD

**Issue by cemeht** [tarampampam/nod32-update-mirror#88]
Здравствуйте!
Очень хотелось бы попробовать воспользоваться вашим творением.
в Docker не силён.
readme.md ничего не описывает.
Не могли бы вы написать полноценный "how to" по запуску и использованию данного контейнера? И можно ли без докера просто на nginx запустить?
Спасибо.

**Comment by tarampampam** [comment]
Проект находится в стадии "переписываю с bash на go", и в связи с нехваткой свободного времени - делаю в условно-свободное время. В данный момент проект ещё не готов к запуску в принципе (он не дописан)
