### ISSUE TITLE
At startup - exited with code 0. Help

### ISSUE THREAD

**Issue by wirtor** [tarampampam/nod32-update-mirror#90]
When I try to start, I get the following message:
eset_update@esetupdate:~/distr/nod32-update-mirror-master$ sudo docker-compose up
Recreating nod32-update-mirror-master_golint_1 ... done
Recreating nod32-update-mirror-master_app_1    ... done
Attaching to nod32-update-mirror-master_app_1, nod32-update-mirror-master_golint_1
nod32-update-mirror-master_app_1 exited with code 0
nod32-update-mirror-master_golint_1 exited with code 0

**Comment by tarampampam** [comment]
This project is under WIP and temporarily abandoned (I have no enough time for it), sorry for this :(
